events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # File statici uploads
        location /uploads/ {
            alias /usr/share/nginx/uploads/;
            expires 30d;
            add_header Cache-Control "public, immutable";
        }

        # SPA admin
        location /admin {
            root /usr/share/nginx/admin;
            try_files $uri $uri/ /index.html;
        }

        # API backend
        location /api/ {
            proxy_pass http://spring-app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # SPA pubblica
        location / {
            root /usr/share/nginx/public;
            try_files $uri $uri/ /index.html;
        }
    }
}